# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          docker build ./buildenv --tag buildenv
          docker build ./openocd --tag openocd
          docker build ./daplink --tag daplink
          mkdir outputs
          docker run -it --rm -v `pwd`/outputs:/outputs --entrypoint cp openocd -a /openocd-win    /outputs/openocd-win 
          docker run -it --rm -v `pwd`/outputs:/outputs --entrypoint cp openocd -a /openocd-native /outputs/openocd-linux
          docker run -it --rm -v `pwd`/outputs:/outputs --entrypoint cp daplink src/Seeed_Arduino_DAPLink/examples/custom_pins/Seeeduino_XIAO_DAPLink.uf2 /outputs/
          mkdir artifacts
          cd outputs
          tar cf ../artifacts/openocd-linux.tar.gz openocd-linux
          zip ur ../artifacts/openocd-win.zip openocd-win
          cp Seeeduino_XIAO_DAPLink.uf2 ../artifacts/
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: artifacts/
