# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          docker build ./buildenv --tag buildenv
          docker build ./openocd --tag openocd
          docker build ./daplink --tag daplink
          mkdir artifacts
          docker run --rm -v `pwd`/outputs:/outputs --entrypoint zip openocd -rq - /openocd-win > artifacts/openocd-win.zip 
          docker run --rm -v `pwd`/outputs:/outputs --entrypoint sh openocd -c "mv /openocd-native /openocd-linux && tar zcf - -C / openocd-linux" > artifacts/openocd-linux.tar.gz
          docker run --rm -v `pwd`/outputs:/outputs --entrypoint cat daplink src/Seeed_Arduino_DAPLink/examples/custom_pins/Seeeduino_XIAO_DAPLink.uf2 > artifacts/Seeeduino_XIAO_DAPLink.uf2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: artifacts/
